name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-push:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Setup Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Build Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/my-app:latest
            ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.run_id }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/my-app:latest
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/my-app:latest,mode=max
          provenance: false

  deploy-self:
    name: Deploy Docker Image on Self-Hosted
    needs: build-and-push 
    runs-on: pi5
    steps:
      - name: Deploy Docker Image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          docker stop my-container || true
          docker rm my-container || true
          docker run -d -p 81:81 --name my-container ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          
  deploy-ubuntu:
    name: Deploy Docker Image on Ubuntu
    needs: build-and-push 
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Docker Image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          docker run -d -p 81:81 ${{ secrets.DOCKER_USERNAME }}/my-app:latest
