name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-push:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.run_id }} \
            --push \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            .

  deploy-self:
    name: Deploy Docker Image on Self-Hosted
    needs: build-and-push 
    runs-on: pi5
    
    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      # Step 2: Pull and Deploy Docker Image
      - name: Deploy Docker Image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          docker run -d -p 81:81 ${{ secrets.DOCKER_USERNAME }}/my-app:latest
  deploy-ubuntu:
    name: Deploy Docker Image on Ubuntu
    needs: build-and-push 
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      # Step 2: Pull and Deploy Docker Image
      - name: Deploy Docker Image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/my-app:latest
