name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-push:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pip-cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Build and Push Multi-Architecture Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64/v8 \
            --cache-from type=registry,ref=${{ secrets.DOCKER_USERNAME }}/my-app-cache:latest \
            --cache-to type=registry,ref=${{ secrets.DOCKER_USERNAME }}/my-app-cache:latest,mode=max \
            -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.run_id }} \
            --push \
            .

  deploy-self:
    name: Deploy Docker Image on Self-Hosted
    needs: build-and-push 
    runs-on: pi5
    steps:
      - name: Deploy Docker Image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          docker stop my-container || true
          docker rm my-container || true
          docker run -d -p 81:81 --name my-container ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          
  deploy-ubuntu:
    name: Deploy Docker Image on Ubuntu
    needs: build-and-push 
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Docker Image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          docker run -d -p 81:81 ${{ secrets.DOCKER_USERNAME }}/my-app:latest
